signin & signup
Opportunity-Nexus/Opportunity-Nexus pull request #1
Opened 2023-11-01 13:03 UTC by KingAman26

2023-11-01 13:09 UTC, Sheetal-04 submitted a review, later dismissed

2023-11-01 18:23 UTC, Nandani-Paliwal commented
<img width="472" alt="Screenshot 2023-11-01 at 11 52 20 PM" src="https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/485b4b94-a642-4c51-b33c-16555579e80a">

Login page should not have confirmed password data field, this field must belongs to signup page. 

You can refer to different site login page if require . example: github.com

2023-11-01 18:24 UTC, Nandani-Paliwal commented
<img width="634" alt="Screenshot 2023-11-01 at 11 53 57 PM" src="https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/ae8fbec3-8917-4d84-9d7f-e65178a8510e">
Add confirmed password field in this form.

2023-11-01 18:25 UTC, Nandani-Paliwal commented
<img width="541" alt="Screenshot 2023-11-01 at 11 54 38 PM" src="https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/55b5289d-0f1e-4ab6-9ea3-f3d3b5b973a1">
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/7596419e-3443-4ac3-be8e-19dbc89abe63)
Refer to second image, the same way it has a don't have a account prompt, add a prompt on signup page asking if already have an account, login here

2023-11-01 18:26 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/0b7d4550-f1c6-420f-b909-1572e529290e)
Clicking on signup here, leads to this error, redirect the user to signup page
<img width="444" alt="Screenshot 2023-11-01 at 11 56 30 PM" src="https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/4335a551-66e7-4a67-a08b-786a9f355c8d">

2023-11-01 18:27 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/61f95a01-fc5a-4b72-8d8d-87ea7e94b6fd)
fix responsiveness

2023-11-01 18:28 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/b7f29566-e9d1-4955-99b6-1752d6290df5)
same for mobile, fix responsiveness.

2023-11-01 18:28 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/ea0b5fa8-aad9-4786-ad55-7a0484fc2aba)
change the color of this icon to white in dark mode.

2023-11-01 18:30 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/3b14bf09-6e07-453d-835d-c88ab712d619)
check for the height of the body here and fix it, this is not visible in light mode, bcs of the color blend

2023-11-01 18:46 UTC, Nandani-Paliwal requested changes
Changes requested 👍

2023-11-01 18:46 UTC, Nandani-Paliwal commented on .DS_Store
delete this file

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +                  required=""
required should be of boolean type not a string.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +            <form className="space-y-4 md:space-y-6" action="#">
form submission handling missing ?
dont worry about the backend call just skip the backend call but handle rest of the frontend things please.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +                  required=""
required should be boolean , please fix this and check wherever applicable

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +                  for="confirm-password"
as told remove this field from here and move to signup form

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +                  type="confirm-password"
`confirm-password` is not valid input type this should be `password` only.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +                      href="www.google.com"
google.com ??

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +const Signin = () => {
this component should have state change handling as well, as I can see there is no local state being handled for input elements, how would be even record the data being entered by the user and send it to backend ? Please handle it.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +            <form className="space-y-4 md:space-y-6" action="#">
Add state using useState hook and change the data on onChange event listener of every input element

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +                  type="password"
add basic client side data validation. 
like email should be valid,
passwords minimum character length etc. ?
These checks are necessary on both backend and frontend with security and best practice view.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +              <button
add button disable states.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signin.jsx
> +                  href="www.google.com"
google.com ? 
redirect to signup page from here instead of www.google.com

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/Components/Account/Signup.jsx
> +const Signup = () => {
check for the Signin page comments, all the comment changes applies here too.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/.DS_Store
remove the uneccessary file.

2023-11-01 18:46 UTC, Nandani-Paliwal commented on src/assets/.DS_Store
remove this file

2023-11-01 18:46 UTC, Nandani-Paliwal commented on package.json
> +    "react-hot-toast": "^2.4.1",
why they are added, I cant see the usage anywhere in the code below?

2023-11-04 05:33 UTC, Sheetal-04 approved these changes

2023-11-04 07:48 UTC, Sheetal-04 requested changes, later dismissed

2023-11-04 07:48 UTC, Sheetal-04 commented on .DS_Store
put this file in  .gitignore  to untrack .

2023-11-04 07:48 UTC, Sheetal-04 commented on src/.DS_Store
put this file in .gitignore to untrack .

2023-11-04 07:48 UTC, Sheetal-04 commented on src/Components/Template.jsx
Here Change one thing ,  on both the pages (signup and login)  sign in with google is showing ,change it to Continue with google .

2023-11-04 07:48 UTC, Sheetal-04 commented on src/assets/.DS_Store
put this file in .gitignore to untrack .

2023-11-04 07:48 UTC, Sheetal-04 commented on src/assets/team/.DS_Store
put this file in .gitignore to untrack .

2023-11-04 07:48 UTC, Sheetal-04 commented on src/Components/LoginForm.jsx
Here one thing more that redirect forget password to some page means make that one .

2023-11-04 18:26 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/7b6efca4-b2c5-43e2-8979-cc72834e03c0)
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/d5a50fc1-0acc-44d9-a0a5-8047e20fd425)

center align image vertically with respect to form 
also here yellow color is not going with the theme, chnage it to some other shade of blue since our website is blue themed.

2023-11-04 18:27 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/e4877931-c7f7-4020-a725-0cc364d29977)
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/7007d6c5-9278-45cf-81bc-202766ee6a9b)
the whole component of signin or signup is not center align

2023-11-04 18:33 UTC, Nandani-Paliwal commented
Resolve conflicts !

2023-11-04 18:53 UTC, Nandani-Paliwal commented
Add proper validation like (use regex check)

2023-11-04 19:31 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/e6710a3d-f0af-4a84-bcba-a787e7f9c586)
text color should be black and not light gray like placeholder

2023-11-05 10:28 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/8ac39b5b-c14a-455e-bf91-b337b8326ddb)
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/d70e0844-8d5c-461c-b809-a643263752a8)

chnage the text color to white, like it is in forgot password page 
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/0e1abc2d-edee-4bc4-9532-0a7cec8077d9)

2023-11-05 10:31 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/65de89fb-ae44-4967-ba40-766a717779e5)
change text color to white, will be more visible then

2023-11-05 10:36 UTC, Nandani-Paliwal submitted a review, later dismissed
Expect these changes everything looks good to me.

2023-11-05 11:34 UTC, Sheetal-04 approved these changes

2023-11-05 11:34 UTC, merged