Fixed : Team section , Mentor Section , Navigation of FAQ
Opportunity-Nexus/Opportunity-Nexus pull request #10
Opened 2024-01-24 20:52 UTC by Sheetal-04

2024-01-25 16:22 UTC, Nandani-Paliwal requested changes

2024-01-25 16:22 UTC, Nandani-Paliwal commented on src/Components/hero/index.jsx
> +                  <div className="flex justify-center items-center text-center dark:bg-black shadow-md dark:text-white text-[16px] font-normal rounded-lg px-2 py-1 w-fit mx-0 sm:mx-auto lg:mx-0">
use `text-base` in place of `text-[16px]`

2024-01-25 16:22 UTC, Nandani-Paliwal commented on src/Components/mentors-word/index.jsx
> +                    <p className="text-lg font-bold text-primary-900 dark:text-primary-500">
change the color from `primary-900` to `text-white` same as opportunityNexus

2024-01-26 06:43 UTC, Nandani-Paliwal requested changes, later dismissed

2024-01-26 06:43 UTC, Nandani-Paliwal commented on src/Components/team/index.jsx
>      twitterUrl: "#",
remove it if he doesn't have a twitter account

2024-01-26 06:49 UTC, Nandani-Paliwal commented
@Sheetal-04  pull the changes of `main` branch into `minor-fixes`

2024-01-27 13:54 UTC, KingAman26 approved these changes

2024-01-27 13:55 UTC, merged