Allignment of authencation pages
Opportunity-Nexus/Opportunity-Nexus pull request #15
Opened 2024-03-07 17:35 UTC by KingAman26

2024-03-07 17:52 UTC, Sheetal-04 requested changes

2024-03-07 17:52 UTC, Sheetal-04 commented on src/Pages/Authentication/ForgetPass.jsx
Make the Heading at center.Allignment is not proper
![Screenshot 2024-03-07 230920](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/59adef28-fa3f-4c97-a9b3-a2bc5f2aecf7)


Also Do the loader at center that is not properly center .
Also Add the email validation here (.com) issue

2024-03-07 17:58 UTC, Sheetal-04 requested changes

2024-03-07 17:58 UTC, Sheetal-04 commented on src/Pages/Authentication/UpdatePassword.jsx
Your Update Password changes are not reflecting .

2024-03-08 05:08 UTC, KingAman26 commented on src/Pages/Authentication/ForgetPass.jsx
please upload loader image ,where it is not center

2024-03-09 03:58 UTC, Nandani-Paliwal commented
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/d767f894-da94-43e1-a896-3f65f53be94f)

- Dont bold the paragraph text, give more margin to paragraph, and set min-width in it so that it doesn't expand like this also set the text color in a shade of gray 
- For email input, make sure that it won't expand like this on the whole page, and try to make the width of `Reset Password` the same as the email input so it will look clean
- Remove the shadow from the div, it will look good
- Also add a Footer.

Ig with these changes the UI will look more subtle and clean

2024-03-09 04:02 UTC, Nandani-Paliwal requested changes
![image](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/8d2c12ed-35ee-4d08-8594-3cac684d6f67)

Here also the same changes I suggested for Reset Password page 

- Dont bold the paragraph text, give more margin to paragraph, and set min-width in it so that the text wrap up and will look good also set the text color in a shade of gray
- Remove the shadow from the div, it will look good.
- Add a Footer.

2024-03-09 04:03 UTC, Nandani-Paliwal commented
![Screenshot from 2024-03-09 09-28-31](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/83964826/b270e13c-eb65-4cf0-84a7-4131f7ff5a45)

Remove shadow

2024-03-09 06:07 UTC, Sheetal-04 requested changes

2024-03-09 06:07 UTC, Sheetal-04 commented on src/Pages/Authentication/UpdatePassword.jsx
![Screenshot 2024-03-09 112933](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/d9fb3906-8d39-49de-80ae-eff92cc8c447)
I think you should reduce the gap between tha btn and para else this component is ok.

2024-03-09 06:07 UTC, Sheetal-04 commented on src/Pages/Authentication/ForgetPass.jsx
![Screenshot 2024-03-09 113014](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/d13b34ad-cdc1-414f-8568-cc20504aa87d)
Now it is looking good but in dark theme in my POV add some border because that shadow is not properly visible as light theme or you can choose the option of changing the background color of the div .
For reference : See the opportunity Dropdown -> Other Component 

Else Looking fine  and also remove the shadow from the loader

2024-03-09 07:28 UTC, Sheetal-04 approved these changes
I think this looks better now!
Let others look into this as well.

2024-03-09 08:06 UTC, Nandani-Paliwal requested changes
Remove shadow in light theme, shadow is looking good in dark theme but not in light theme

Rest looks good to me

2024-03-09 13:26 UTC, KingAman26 commented
without shadow its not looking nc ...i think its good with shadow

2024-03-09 16:03 UTC, Nandani-Paliwal commented
> without shadow its not looking nc ...i think its good with shadow if You Guys says i can try adding littile lighter bg color in light theme

ok then let it be..

2024-03-09 16:04 UTC, Nandani-Paliwal approved these changes

2024-03-09 16:41 UTC, merged