feat: add application layout. [Do not merge, Work in progress]
Opportunity-Nexus/Opportunity-Nexus pull request #17
Opened 2024-03-13 15:06 UTC by Nandani-Paliwal

2024-03-13 21:06 UTC, KingAman26 commented
![Screenshot 2024-03-14 at 2 34 31 AM](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/87798432/95dd5a07-ce78-4cb6-b0f4-82c09f694295)

2024-03-13 21:09 UTC, KingAman26 commented
![Screenshot 2024-03-14 at 2 38 37 AM](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/87798432/2a155d29-835a-4d61-866e-725c29d5a2f3)
Icons are not showing on hover fix it

2024-03-13 21:14 UTC, KingAman26 commented
![Screenshot 2024-03-14 at 2 38 37 AM](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/87798432/3ea65e67-be5c-405c-83bf-13e297512e3a)
Fix it: Icons are not shown when hovering.

2024-03-13 21:15 UTC, KingAman26 commented
The navigation bar is hidden. How is it possible for anyone to navigate?

2024-03-13 21:36 UTC, Sheetal-04 requested changes

2024-03-13 21:36 UTC, Sheetal-04 commented on src/Common/Layout.jsx
It's totally opposite what i made in the wireframe and also the fields are not same which we are going to put it in our project.

1. You didn't make a seperate data file and also in that data there is no account_type so that on that basis admin_dashboard features will be displayed.

2. Admin Dashboard features didn't covered you have to first look into the wireframe which i have made .
![Screenshot 2024-03-13 183727](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/4d7b0366-2301-41ea-840b-1bd9deabbdd0)

3. In dropdown please take care of alignment name is not in center ,uppercase .
![Screenshot 2024-03-14 023710](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/ec509de3-db09-427d-90a0-f8d31ec2da10)

4.When we are on dashboard on logo set the route to go back to the home page .We are unable to go back to the home page .

5.In dashboard color co-ordination is not proper look into this:
![Screenshot 2024-03-14 023856](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/eb245ce9-e74a-46a8-ba19-dcddc665b1c1)

and now look into this 
![Screenshot 2024-03-14 023912](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/603791b1-a187-4acf-a9b7-340a11953404)

6. Also when the side navbar opens the alignment of the horizontal line mismatches with the Header.
7.Look at the theme icon in side navbar not looking good make the horizontal line proper .
8.You have to look into the wireframe & please take your time but make it ryt.

2024-03-16 16:51 UTC, KingAman26 commented
![Screenshot 2024-03-16 at 10 16 47 PM](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/87798432/4c12da05-86e6-475f-b3c3-147400f9e330)
Make border rounded 
and change bg color its not matching ui

2024-03-16 16:55 UTC, KingAman26 commented
![Screenshot 2024-03-16 at 10 24 21 PM](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/87798432/bd9d9873-a827-4d10-bf08-0baf60ecee5d)
Fix this icons

2024-03-16 16:58 UTC, KingAman26 commented
Dark theme is not working properly when we navigate to dashboard from home page

2024-03-16 17:02 UTC, Nandani-Paliwal commented
> Dark theme is not working properly when we navigate to dashboard from home page

In my Pov that is not even required to store the state of the theme

2024-03-16 17:02 UTC, KingAman26 commented
Remove setting option from dropdown menu and add it to the dashboard's sideNavbar

2024-03-16 17:04 UTC, Nandani-Paliwal commented
> ![Screenshot 2024-03-16 at 10 24 21 PM](https://private-user-images.githubusercontent.com/87798432/313418828-bd9d9873-a827-4d10-bf08-0baf60ecee5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDg0NjAsIm5iZiI6MTcxMDYwODE2MCwicGF0aCI6Ii84Nzc5ODQzMi8zMTM0MTg4MjgtYmQ5ZDk4NzMtYTgyNy00ZDEwLWJmMDgtMGJhZjYwZWNlZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE2NTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTNhM2RhNDgxZjQ5YzM2ODgwNjU3NzdmYzIxNzg5MmM2NTE2ODY5MzVhMTc4NDRmYjA2ZDBmMWZmNDNiZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mKTTcbxuHvOH2YjB1olYrGyk7Tj2S5_59deF1-8mGIA) Fix this icons

We have quite many items that's why it is shrinking, we can remove the logo or if you have nay way to fix it, please suggest

2024-03-16 17:11 UTC, Nandani-Paliwal commented
> ![Screenshot 2024-03-16 at 10 16 47 PM](https://private-user-images.githubusercontent.com/87798432/313418455-4c12da05-86e6-475f-b3c3-147400f9e330.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDkxNzgsIm5iZiI6MTcxMDYwODg3OCwicGF0aCI6Ii84Nzc5ODQzMi8zMTM0MTg0NTUtNGMxMmRhMDUtODZlNi00NzVmLWIzYzMtMTQ3NDAwZjllMzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE3MDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZjNhNjkzOGZhNDYwOTU2MTJiYmEyZDAxNDY3NzZlYjUwNjAyYTg3OTZhMWI1YTI2MTE3MDE1NjkxMzg0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dkyzZc6kmdTB9yjrWYigtTSNDWTWyOtRlePhtfNSA5Y) Make border rounded and change bg color its not matching ui

This is not something we handle, this is default autocomplete option by browser provide, we can not handle the colour shades of autocomplete provided by browser. Even this is nothing of a concern to do as of now, until unless we actually implement the search engine integrations in here. This is just a UI a implementation of search bar, which is not functional for obvious reasons. 

Rounded means the border radius to search bar or to the "browser provided autocomplete dropdown" ?

2024-03-16 17:24 UTC, Nandani-Paliwal commented
> Remove setting option from dropdown menu and add it to the dashboard's sideNavbar

Removing setting option from dropdown menu and adding it to the dashboard sidebar which is  the "Application layout only" , which ultimately "blocks the user navigation", suppose in a case where user won't be able to find the setting option when in opportunities page which is again on the standard layout, not inside the usual fundamental application layout. 

In general scenarios, companies keep the home page / landing pages of the web products as a source of marketing only, that's the reason they blocks the landing page after a user logs in, because fundamentally landing pages are meant for "user acquisition" not to serve the application and business logic.  Now here in our case same as the scenario becoming a blocker for us because we are not letting people get completely into application layout, hence we need to keep the important link in the upper navbar dropdown only. 

Ideally as I earlier mentioned, we must block the user's access to main landing page as soon as the user logs in, because the agenda of a technical product is to acquire user, which gets met  as soon as the user register, then what's the point of again pitching the user your abilities to serve, which is equivalent to over selling in some ways.

But if you still think it's not relevant to keep the settings link in upper navbar, we can move it to the application layout sidebar .

2024-03-16 17:41 UTC, KingAman26 commented
keep the setting option in both  sidenavbar and dropdown ....as discussed in meet yesterday

2024-03-16 18:08 UTC, Sheetal-04 requested changes

2024-03-16 18:08 UTC, Sheetal-04 commented on src/Common/ApplicationLayout.jsx
I have few things to point out->

1. Theme is not in sync when navigating to another page (It is an error ,i have also faced it ,It is happening because on navigating , the complete component re-renders which is causing this error may be check anchor tag because that cause the complete component to re-render .)
2. Add the settings option as "My Settings" in the sidebar also .
3. I Suggest Please remove the Home option from the dropdown may be i am not getting the reason why you added it ,if any specific please mention.
4. In Dashboard please fix the position of navbar that will be good .
5. On small screen when logo is shrinking i suggest hide that on small screen that will also fix the UI of search bar because when on small screen when we type something on search bar that is not visible so this problem will be automatically resolved.
![Screenshot 2024-03-16 233726](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/5d1cbc04-9b1d-46c9-9c52-d56eb39045d2)

2024-03-17 16:49 UTC, Nandani-Paliwal commented on src/Common/ApplicationLayout.jsx
> I Suggest Please remove the Home option from the dropdown may be i am not getting the reason why you added it ,if any specific please mention.

This home button has been added to make sure, even on dashboard if so now we have a unblocked landing page, not all user's do know that if they need to go back to the home (landing page), they are suppose to click on the logo, with that said, I added a home ref button in the dropdown menu. Let me know if we should remove that. 

> On small screen when logo is shrinking i suggest hide that on small screen that will also fix the UI of search bar because when on small screen when we type something on search bar that is not visible so this problem will be automatically resolved.

One more reason to keep the home link in the dropdown, if we remove the logo from small screen, then there won't be any way to back with clear instinctive for home link. So as we keeping  the home button is necessary. I will remove the logo from the navbar on smaller screens.

> In Dashboard please fix the position of navbar that will be good .

Please add a reference screenshot, which position you are referring to.

> Theme is not in sync when navigating to another page (It is an error ,i have also faced it ,It is happening because on navigating , the complete component re-renders which is causing this error may be check anchor tag because that cause the complete component to re-render .)

Yes, that's because we are deliberately re-rendering the whole document (to hard navigate to let the layout re-render), due to the soft nav limitation of the layouts, let's keep it this way only, until we figure out some way to layout shift on softnav.

2024-03-19 15:52 UTC, Sheetal-04 approved these changes

2024-03-19 15:58 UTC, KingAman26 approved these changes

2024-03-19 17:06 UTC, merged