minor UI changes
Opportunity-Nexus/Opportunity-Nexus pull request #3
Opened 2023-11-06 18:55 UTC by Nandani-Paliwal

2023-11-16 06:35 UTC, Sheetal-04 requested changes

2023-11-16 06:35 UTC, Sheetal-04 commented on src/Components/hero/index.jsx
![Rev-2](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/f5f4fe60-6760-4f8e-834c-bf561115deac)

![Rev-1](https://github.com/Opportunity-Nexus/Opportunity-Nexus/assets/95533641/62641041-05c1-4f8d-8385-766ccee7a0d5)
Changes in this file making the gap above and below not equal.

2023-11-30 17:34 UTC, Nandani-Paliwal commented on src/Components/hero/index.jsx
The spacing between the two is proper it might be  not visible in your screen resolution

2023-12-01 06:05 UTC, Sheetal-04 approved these changes

2023-12-01 06:05 UTC, merged